# Generated by Django 4.2.5 on 2023-10-11 08:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('uuid', models.UUIDField(editable=False)),
                ('shrine_name', models.CharField(max_length=20)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), size=2)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('omamori_picture', models.FileField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
