# Generated by Django 4.2.5 on 2023-10-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omamori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='username',
            field=models.CharField(max_length=30),
        ),
    ]
