# Generated by Django 4.2.5 on 2023-12-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omamori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.CharField(editable=False, max_length=200, primary_key=True, serialize=False, unique=True),
        ),
    ]
