# Generated by Django 4.2.3 on 2023-07-07 08:07

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('omamori', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='Omamori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shrine_name', models.CharField(max_length=200)),
                ('location', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=6, max_digits=9), size=2)),
                ('description', models.CharField(blank=True, max_length=300)),
                ('users_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='omamori.users')),
            ],
        ),
    ]
