# Generated by Django 4.2.5 on 2023-10-11 02:30

import django.contrib.postgres.fields
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('omamori', '0002_alter_users_email_omamori'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='email',
        ),
        migrations.RemoveField(
            model_name='users',
            name='id',
        ),
        migrations.AddField(
            model_name='users',
            name='description',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='users',
            name='location',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(
                decimal_places=6, max_digits=9), default=[35.6764, 139.6993], size=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='omamori_picture',
            field=models.FileField(default='picture.url', upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='shrine_name',
            field=models.CharField(default='Meji Jingu', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='uuid',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, serialize=False),
        ),
        migrations.DeleteModel(
            name='Omamori',
        ),
    ]
