# Generated by Django 4.2.5 on 2023-10-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omamori', '0003_remove_users_email_remove_users_id_users_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='uuid',
            field=models.UUIDField(editable=False),
        ),
    ]
