name: Django CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.11]

    services:
      postgres:
        image: postgres:12.14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run migrations
        run: python manage.py migrate
        env:
          AWS_STORAGE_BUCKET_NAME: ${{secrets.AWS_STORAGE_BUCKET_NAME}}
          AWS_SECRETE_ACCESS_KEY: ${{secrets.AWS_SECRETE_ACCESS_KEY}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_S3_REGION_NAME: ${{secrets.AWS_S3_REGION_NAME}}
          AWS_S3_CUSTOM_DOMAIN: ${{secrets.AWS_S3_CUSTOM_DOMAIN}}
          AWS_CLOUDFRONT_KEY_ID: ${{secrets.AWS_CLOUDFRONT_KEY_ID}}
          AWS_CLOUDFRONT_KEY: ${{secrets.AWS_CLOUDFRONT_KEY}}
      - name: Run Tests
        run: |
          python manage.py test
        env:
          AWS_STORAGE_BUCKET_NAME: ${{secrets.AWS_STORAGE_BUCKET_NAME}}
          AWS_SECRETE_ACCESS_KEY: ${{secrets.AWS_SECRETE_ACCESS_KEY}}
          AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          AWS_S3_REGION_NAME: ${{secrets.AWS_S3_REGION_NAME}}
          AWS_S3_CUSTOM_DOMAIN: ${{secrets.AWS_S3_CUSTOM_DOMAIN}}
          AWS_CLOUDFRONT_KEY_ID: ${{secrets.AWS_CLOUDFRONT_KEY_ID}}
          AWS_CLOUDFRONT_KEY: ${{secrets.AWS_CLOUDFRONT_KEY}}
